name: devcontainer

x-tekforum-common: &tekforum-common
  environment: &tekforum-common-env
    DBT_PROJECT_DIR: ${DBT_PROJECT_DIR}
    DBT_PROFILES_DIR: ${DBT_PROFILES_DIR}
    POSTGRES_HOST: ${POSTGRES_HOST}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

services:

  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    environment:
      <<: *tekforum-common-env

    command: sleep infinity

  postgres-dbt:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      <<: *tekforum-common-env

  pg-admin:
    image: dpage/pgadmin4:8.11
    restart: always
    depends_on:
      - postgres-dbt
    ports:
      - 5050:80
    environment:
      <<: *tekforum-common-env


volumes:
  postgres-db-volume: